version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: quizapp
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpass
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: quizuser
      DB_PASSWORD: quizpass
