version: '3.9'

services:
  db:
    image: postgres:15
    container_name: quizapp-db
    environment:
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpass
      POSTGRES_DB: quizdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: quizapp-web
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: quizdb
      DB_USER: quizuser
      DB_PASSWORD: quizpass

volumes:
  db-data:
